import { useData } from '../hooks/useData';

function statusLabel(status) {
  if (status === 'fresh') return 'Fresh';
  if (status === 'missing') return 'Missing';
  return 'Review';
}

export default function DataFreshnessPanel() {
  const { data, loading, error } = useData('data-freshness.json');

  if (loading || !data) {
    return <div className="card loading-card"><div className="spinner" /><span>Loading source audit…</span></div>;
  }
  if (error) return null;

  const datasets = data.datasets || [];

  return (
    <section className="data-freshness card">
      <div className="data-freshness__header">
        <div>
          <h3>Data Freshness & Source Audit</h3>
          <p>Official-source status generated by the weekly update pipeline.</p>
        </div>
        <span className={`freshness-badge freshness-badge--${data.status}`}>
          <span className="freshness-badge__dot" />
          {statusLabel(data.status)}
        </span>
      </div>

      <div className="freshness-grid">
        {datasets.map((item) => (
          <a
            key={item.id}
            className="freshness-item"
            href={item.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            title={item.expectedLag}
          >
            <div className="freshness-item__top">
              <strong>{item.label}</strong>
              <span className={`freshness-status freshness-status--${item.status}`}>
                {statusLabel(item.status)}
              </span>
            </div>
            <div className="freshness-item__meta">
              <span>Latest: {item.latestObservation || 'N/A'}</span>
              <span>Updated: {item.dashboardUpdated || 'N/A'}</span>
              <span>{item.source}</span>
            </div>
          </a>
        ))}
      </div>
    </section>
  );
}
